christore/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'products.views.home', name = 'home'),
    url(r'^s/$', 'products.views.search', name='search'),
    url(r'^products/$', 'products.views.all', name='products'),
    url(r'^products/(?P<slug>[\w-]+)/$', 'products.views.single', name='single'),
    url(r'^basket/(?P<id>\d+)/$', 'basket.views.remove_from_basket', name='remove_from_basket'),
    url(r'^basket/(?P<slug>[\w-]+)/$', 'basket.views.add_to_basket', name='add_to_basket'),
    url(r'^basket/$', 'basket.views.view', name='basket'),
    url(r'^checkout/$', 'orders.views.checkout', name='checkout'),
    url(r'^orders/$', 'orders.views.orders', name='user_orders'),
    url(r'^ajax/dismizz_marketing_message/$', 'marketing.views.dismiss_marketing_message', name='dismiss_marketing_message'),
    url(r'^ajax/email_signup/$', 'marketing.views.email_signup', name='ajax_email_signup'),
    url(r'^ajax/add_user_address/$', 'accounts.views.add_user_address', name='ajax_add_user_address'),
    url(r'^accounts/logout/$', 'accounts.views.logout_view', name='auth_logout'),
    url(r'^accounts/login/$', 'accounts.views.login_view', name='login'),
    url(r'^accounts/register/$', 'accounts.views.registration_view', name='auth_register'),
    url(r'^accounts/address/add/$', 'accounts.views.add_user_address', name='add_user_address'),
    url(r'^accounts/activate/(?P<activation_key>\w+)/$', 'accounts.views.activation_view', name='activation_view'),

] 

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.core.urlresolvers import reverse
from django.db import models

# Create your models here.
class Catalog(models.Model):
	name = models.CharField(max_length=255)
	slug = models.SlugField(max_length=150)
	description = models.TextField(null=True, blank = True)
	pub_date = models.DateTimeField(auto_now_add=True)
	def __str__(self):
		return self.name

class CatalogCategory(models.Model):
	catalog = models.ForeignKey('Catalog',
	                         related_name='categories')
	parent = models.ForeignKey('self', blank=True, null=True,
	                         related_name='children')
	name = models.CharField(max_length=300)
	slug = models.SlugField(max_length=150)
	description = models.TextField(blank=True)
	featured = models.BooleanField(default = None)
	timestamp = models.DateTimeField(auto_now_add=False, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	active = models.BooleanField(default=True)

	def __str__(self):
		if self.parent:
		    return '%s: %s - %s' % (self.catalog, self.parent, self.name)
		return '%s: %s' % (self.catalog, self.name)


class Product(models.Model):
	title = models.CharField(max_length=60)
	category = models.ForeignKey('CatalogCategory')
	slug = models.SlugField(unique=True)
	description = models.TextField(null=True, blank = True)
	direction = models.TextField(null=True, blank = True)
	warning = models.TextField(null=True, blank = True)
	ingredient = models.TextField(null=True, blank = True)
	review = models.TextField(null=True, blank = True)
	price = models.DecimalField(max_digits=10, decimal_places=2, default=99.99)
	sale_price = models.DecimalField(decimal_places=2, max_digits=10, null = True, blank = True)
	timestamp = models.DateTimeField(auto_now_add=False, auto_now=True)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	active = models.BooleanField(default = True)
	update_defaults = models.BooleanField(default = False)

	def __str__(self):
		return self.title

	class Meta:
		unique_together=('title', 'slug')

	def get_price(self):
		return self.price

	def get_absolute_url(self):
		return reverse("single", kwargs={"slug": self.slug})

class ProductImage(models.Model):
	product = models.ForeignKey('Product')
	image = models.ImageField(upload_to='img/products')
	featured = models.BooleanField(default=False)
	thumbnail = models.BooleanField(default=False)
	active = models.BooleanField(default=True)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)

	def __str__(self):
		return self.product.title

# def product_defaults(sender, instance, created, *args, **kwargs):
# 	if instance.update_defaults:
# 		categories = instance.category.all()
# 		print (categories)
# 		for cat in categories:
# 			print (cat.id)
# 			if cat.id == !


class VariationManager(models.Manager):
	def all(self):
		return super(VariationManager, self).filter(active=True)

	def sizes(self):
		return self.all().filter(category='size')

	def colors(self):
		return self.all().filter(category='color')


VAR_CATEGORIES = (
	('size', 'size'),
	('color', 'color'),
	('package', 'package'),
	)


class Variation(models.Model):
	product = models.ForeignKey(Product)
	category = models.CharField(max_length=120, choices=VAR_CATEGORIES, default='size')
	title = models.CharField(max_length=120)
	image = models.ForeignKey(ProductImage, null=True, blank=True)
	price = models.DecimalField(max_digits=100, decimal_places=2, null=True, blank=True)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	active = models.BooleanField(default=True)

	objects = VariationManager()

	def __str__(self):
		return self.title

products/views.py
from django.shortcuts import render, Http404

# Create your views here.
from .models import Product, ProductImage

def search(request):
	try:
		q = request.GET.get('q')
	except:
		q = None
	
	if q:
		products = Product.objects.filter(title__icontains=q)
		context = {'query': q, 'products': products}
		template = 'products/results.html'	
	else:
		template = 'products/home.html'	
		context = {}
	return render(request, template, context)

def home(request):
	products = Product.objects.all()
	template = "products/home.html"
	context = {
		"products": products,
	}
	return render(request, template, context)

def single(request, slug):
	try:
		product = Product.object.get(slug = slug)
		#images = product.productimage_set.all()
		images = ProductImage.objects.filter(product=product)
		context = {"product": product, "images": images}
		template = "products/single.html"
		return render(request, template, context)
	except:
		raise Http404

def all(request):
	products = Product.objects.all()
	context = {'products': products}
	template = 'products/all.html'
	return render(request, template, context)

templates/products/all.html
{% extends 'base.html' %}


{% load staticfiles %}

{% block head_title %}
Products || 
{% endblock %}

{% block styles %}
.jumbotron {
	/*color: red;*/
}
{% endblock %}


{# Comments here #}


{% block content %}




<div class='row'>

{% for product in products %}
		<div class='col-sm-2'>



			<div class="thumbnail">
					{% if product.productimage_set.all %}

							{% for item in product.productimage_set.all %}

							{% if item.featured %}
							<div style="width:100px;margin:0 auto;">

								<a href='{{ product.get_absolute_url }}'>
									<div class='background_img_thumb' style="height:100px;background-image: url('{{ MEDIA_URL }}{{ item.image }}');"></div>
								</a>
							</div>
							<!-- <img class='img-responsive' src="{{ MEDIA_URL }}{{ item.image }}" /> -->
							{% endif %}
							 


							{% endfor %}

					{% else %}
					<div style="width:100px;margin:0 auto;">

								<a href='{{ product.get_absolute_url }}'>
									<div class='background_img_thumb' style="height:100px;"></div>
								</a>
							</div>
					{% endif %}

					<div class="caption">
					<a href='{{ product.get_absolute_url }}'> <h3>{{ product.title }}</h3></a>
					<p>{{ product.description|truncatewords:15}}</p>
					<p><a href="{{ product.get_absolute_url }}" class="btn btn-primary" role="button">View</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
					</div>
		   	 </div>


		</div>

{% cycle "" "" "" "" "" "</div><br/><hr/><div class='row'>" %}
{% endfor %}

</div>

{% endblock %}

templates/products/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_title %}
Welcome to 
{% endblock %}

{% block styles %}
.jumbotron {
	/*color: red;*/
}
{% endblock %}

{% block jquery %}
//alert("welcome!");
{% endblock%}

{# Comments here #}


{% block jumbotron2 %}
  <div class="container">

			<!-- Main component for a primary marketing message or call to action -->
			<div class="jumbotron">
			<h1> Hello {{ username_is }}</h1>
			<p>This example is a quick exercise to illustrate how the default, static and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
			<p>To see the difference between static and fixed top navbars, just scroll.</p>
			<p>
			<a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">View navbar docs &raquo;</a>
			</p>
			</div>
  </div>
{% endblock %}


{% block jumbotron %}
{% if sliders %}
  <div class='container' style='margin-top: -19px;margin-bottom: 19px;'>
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
           {% for slider in sliders %}
            <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter }}"{% if forloop.first %}class="active"{% endif %}>
            </li>
            {% endfor %}
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">

            {% for slider in sliders %}
              <div class="item {% if forloop.first %}active{% endif %}">
                {% if slider.url_link %}<a href='{{ slider.url_link }}'>{% endif %}
              <img src="{{ slider.get_image_url }}" alt="...">
                {% if slider.url_link %}</a>{% endif %}
              <div class="carousel-caption">
                  {% if slider.header_text %}
                  <h1>{{ slider.header_text|safe }}</h1>
                  {% endif %}
                  {% if slider.text %}
                  <p>{{ slider.text|safe }}</p>
                  {% endif %}
            
              </div>
            </div>

            {% endfor %}
  
          </div>

          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

    </div>

    {% endif %}
{% endblock %}

{% block content %}




<div class='row'>

{% for product in products %}
		<div class='col-sm-4'>



			<div class="thumbnail">
					{% if product.productimage_set.all %}

							{% for item in product.productimage_set.all %}

							{% if item.featured %}
							<div style="
							width:200px;
							height:200px;margin:0 auto;">

								<a href='{{ product.get_absolute_url }}'>
									<div class='background_img_thumb' style="height:200px;background-image: url('{{ MEDIA_URL }}{{ item.image }}');"></div>
								</a>
							</div>
							<!-- <img class='img-responsive' src="{{ MEDIA_URL }}{{ item.image }}" /> -->
							{% endif %}
							 


							{% endfor %}

					{% else %}
					<img class='img-responsive' src='{% static "img/placeholder.svg" %}' />
					{% endif %}

					<div class="caption">
					<a href='{{ product.get_absolute_url }}'> <h3>{{ product.title }}</h3></a>
					<p>{{ product.description|truncatewords:15}}</p>
					<p><a href="{{ product.get_absolute_url }}" class="btn btn-primary" role="button">View</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
					</div>
		   	 </div>


		</div>

{% cycle "" "" "</div><br/><hr/><div class='row'>" %}
{% endfor %}

</div>

{% endblock %}

templates/products/results.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block content %}

<h1>Searched for: {{ query }}</h1>

{{ products }}

<table class='table'>
<thead>
<th></th>
<th>Product</th>
</thead>

<tbody>
{% for product in products %}
	<tr>
	<td style="width:160px; height:160px;">

	{% if product.productimage_set.all %}
		{% for item in product.productimage_set.all %}
			{% if item.featured %}

	<!-- <div style='width:100%; height:100%;
	background-image: url("{{ MEDIA_URL }}{{ item.image }}");
	background-size:cover;background-repeat:no-repeat; background-position:center;'></div>
 -->
 	<a href='{{ product.get_absolute_url }}'>
 		<div class='background_img_thumb' style="height:160px;background-image: url('{{ MEDIA_URL }}{{ item.image }}');"></div>
 	</a>

			{% endif %}
		{% endfor %}

	{% else %}
	<a href='{{ product.get_absolute_url }}'>
	<div class='background_img_thumb' style='height:160px;'></div>
	</a>
<!-- 	<div style='width:100%; height:100%;background-image:url("{% static "img/placeholder.svg" %}");background-size:cover;background-repeat:no-repeat; background-position:center;'></div> -->


	{% endif %}
	</td>
	<td>
	<a href='{{ product.get_absolute_url }}'>{{ product }}</a>
	</td>
	</tr>
{% endfor %}

</tbody>


</table>

{% endblock %}

templates/products/single.html
{% extends 'base.html' %}

<div class="page-header">
  <h1>{{ product.title }}</h1>
</div>

{% block content %}


<div class='row'>
	<div class='col-sm-4'>
	{% for img in images %}

		{% if img.featured %}
		<div class="col-xs-12">
			<img class='img-responsive' src="{{ MEDIA_URL }}{{ img.image }}" />
		<hr/>
		</div>
		{% endif %}
			{% endfor %}
	{% for img in images %}
		{% if not img.featured %}
		<div class="col-xs-6">
	    <a href="#" class="thumbnail">
	      <img class='img-responsive' src="{{ MEDIA_URL }}{{ img.image }}">
	    </a>
	  	</div>

		{% endif %}
								 
	{% endfor %}
	</div>
	<div class='col-sm-8'>
		<div class='col-sm-8 pull-left'>
			 <h1>{{ product.title }} 
			 </h1>
		 </div>
		 <div class='col-sm-4 pull-right'>
			 	 <form class='form' method='POST' action='{% url "add_to_basket" product.slug %}'> {% csrf_token %}
			 	 <input class='btn btn-default btn-block' type='submit' value='Add to basket'/>
			 	<input  class="form-control"  name='qty' type='number' value='1'/>
			 	
			 	{% if product.variation_set.all %}


			 	{% if product.variation_set.sizes %}
			 	<select class='form-control' name='size'>
			 	{% for item in product.variation_set.sizes %}
			 		<option value='{{ item.title|lower }}'>{{ item.title|capfirst }}</option>
			 		{% endfor %}
			 	</select>
			 	{% endif %}

			 	 {% if product.variation_set.colors %}
			 	<select class='form-control' name='color'>
			 	{% for item in product.variation_set.colors %}
			 		<option value='{{ item.title|lower }}'>{{ item.title|capfirst }}</option>
			 		{% endfor %}
			 	</select>
			 	{% endif %}



			 	{% endif %}

			 </form>
	 	</div>
	 	<div class='col-sm-12'>
			 <hr/>

			 Price: {{ product.price }} <br/>
			 Shipping: Free with $25+ purchase.
			 <hr/>
	 	</div>
			 <div class='col-sm-12'>
			{{ product.description|linebreaks }}
				</div>
	</div>
</div>

{% endblock %}