christore/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'products.views.home', name = 'home'),
    url(r'^s/$', 'products.views.search', name='search'),
    url(r'^products/$', 'products.views.all', name='products'),
    url(r'^products/(?P<slug>[\w-]+)/$', 'products.views.single', name='single'),
    url(r'^basket/(?P<id>\d+)/$', 'basket.views.remove_from_basket', name='remove_from_basket'),
    url(r'^basket/(?P<slug>[\w-]+)/$', 'basket.views.add_to_basket', name='add_to_basket'),
    url(r'^basket/$', 'basket.views.view', name='basket'),
    url(r'^checkout/$', 'orders.views.checkout', name='checkout'),
    url(r'^orders/$', 'orders.views.orders', name='user_orders'),
    url(r'^ajax/dismizz_marketing_message/$', 'marketing.views.dismiss_marketing_message', name='dismiss_marketing_message'),
    url(r'^ajax/email_signup/$', 'marketing.views.email_signup', name='ajax_email_signup'),
    url(r'^ajax/add_user_address/$', 'accounts.views.add_user_address', name='ajax_add_user_address'),
    url(r'^accounts/logout/$', 'accounts.views.logout_view', name='auth_logout'),
    url(r'^accounts/login/$', 'accounts.views.login_view', name='login'),
    url(r'^accounts/register/$', 'accounts.views.registration_view', name='auth_register'),
    url(r'^accounts/address/add/$', 'accounts.views.add_user_address', name='add_user_address'),
    url(r'^accounts/activate/(?P<activation_key>\w+)/$', 'accounts.views.activation_view', name='activation_view'),

] 

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from decimal import Decimal
from django.conf import settings
from django.db import models


# Create your models here.
from accounts.models import UserAddress
from basket.models import Basket

STATUS_CHOICES = (
	("Started", "Started"),
	("Abandoned", "Abandoned"),
	("Finished", "Finished"),
	)

try:
	tex_rate = settings.DEFAULT_TAX_RATE
except Exception as e:
	print (str(e))
	raise NotImplementedError(str(e))

class Order(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
	order_id = models.CharField(max_length = 120, default="ABC", unique=True)
	basket = models.ForeignKey(Basket)
	status = models.CharField(max_length=120, choices = STATUS_CHOICES, default="Started")
	shipping_address = models.ForeignKey(UserAddress, related_name='shipping_address', default=1)
	billing_address = models.ForeignKey(UserAddress, related_name='billing_address', default=1)
	sub_total = models.DecimalField(default=10.99, max_digits=1000, decimal_places=2)
	tax_total = models.DecimalField(default=10.99, max_digits=1000, decimal_places=2)
	final_total = models.DecimalField(default=10.99, max_digits=1000, decimal_places=2)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)

	def __str__(self):
		return self.order_id

	def get_final_amount(self):
		instance = Order.objects.get(id=self.id)
		two_places = Decimal(10) ** -2
		tax_rate_dec = Decimal("%s" %(tax_rate))
		sub_total_dec = Decimal(self.sub_total)
		tax_total_dec = Decimal(tax_rate_dec * sub_total_dec).quantize(two_places)
		instance.tax_total = tax_total_dec
		instance.final_total = tax_total_dec
		instance.save()
		return instance.final_total

orders/views.py
import time
import stripe

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib import messages
from django.shortcuts import render, HttpResponseRedirect

# Create your views here.
from accounts.forms import UserAddressForm
from accounts.models import UserAddress 
from basket.models import Basket

from .models import Order
from .utils import id_generator



def orders(request):
	context = {}
	template = "orders/user.html"
	return render(request, template, context)

@login_required
def checkout(request):
	try:
		the_id = request.session['basket_id']
		basket = Basket.objects.get(id=the_id)
	except:
		the_id =None
		return HttpResponseRedirect(reverse("basket"))

	try:
		new_order = Order.objects.get(basket=basket)
	except Order.DoesNotExist:
		new_order =Order()
		new_order.basket = basket
		new_order.user = request.user
		new_order.order_id = id_generator()
		new_order.save()
	except:
		new_order = None
		# some error message goes here
		return HttpResponseRedirect(reverse("basket"))
	final_amount = 0
	if new_order is not None:
		new_order.sub_total = basket.sub_total
		new_order.save()
		final_amount = new_order.get_final_amount()

	try:
		address_added = request.GET.get("address_added")
	except:
		address_addd =None

	if address_added is None:
		address_form = UserAddressForm()
	else:
		address_form = None

	current_addresses = UserAddress.objects.filter(user=request.user)
	billing_addresses = UserAddress.objects.get_billing_address(user=request.user)
	print (billing_addresses)

	if request.method == "POST":
		try:
			user_stripe = request.user.userstripe.stripe_id
			customer = stripe.customer.retrieve(user_stripe)
			print (customer)
		except:
			customer = None
			pass
		if customer is not None:
			bill_a = request.POST['billing_address']
			ship_a = request.POST['shipping_address']
			token = request.POST['stripeToken']

			try:
				billing_address_instance = UserAddress.objects.get(id=bill_a)
			except:
				billing_address_instance = None
			try:
				shipping_address_instance = UserAddress.objects.get(id=ship_a)
			except:
				shipping_address_instance = None
			card = customer.card.create(card=token)
			card.address_city = billing_address_instance.city or None
			card.address_line1 = billing_address_instance.address or None
			card.address_line2 = billi.address2 or None
			card.address_state = billing_address_instance.state or None
			card.address_country = billing_address_instance.country or None
			card.address_zip = billing_address_instance.zipcode or None
			card.save()

			charge = stripe.Charge.create(
				amount = int(final_amount ^ 100),
				currency = "usd",
				card = card, #obtasined with Strip.js
				customer = Customer,
				description = "Charge for %s" %(request.user.username)
			)
			if charge["captured"]:
				new_order.status = "finished"
				new_order.shipping_address = shipping_address_instance
				new_order.billing_address = billing_address_instance
				new_order.save()
				del request.session['basket_id']
				del request.session['item_total']
				messages.success(request, "Thanks your order. It has been completed!")
				return HttpResponseRedirect(reverse("user_orders"))

	context = {
	"order": new_order,
	"address_form" :address_form,
	"current_addresses" : current_addresses,
	"billing_addresses" : billing_addresses,
	"stripe_pub" :stripe_pub,
	}
	template = "orders/checkout.html"
	return render(request, template, context)

templates/orders/checkout.html
{% extends "base.html" %}

<script>
{% block jquery %}

$(".radio-label").click(function(){
	$('label').removeClass('radio-label-selected')
	$(this).addClass('radio-label-selected');
});

$(".billin-label").click(function){
	$("label").removeClass('billing-label-selected');
	$(this.addClass('billing-label-selected');
});

	//This identifies caremedics in the create token call below
	Stripe.setPublishableKey('{{ stripe_pub }}');

jQuery(function(S){
	$('#payment-form').submit(function(event){
		var $form = $(this);

		//Disable the submit button to revent repeated clicks
		$form.find('button').prop('disabled', true);

		Strip.card.createToken($form, stripeResponseHandler);

		//Prevent the form from submitting with default action
		return false;

	});
});

function stripeResponseHandler(status, response){
	var $form = $('#payment-form');

	if (response.error){
		//show errors on the form
		$("#card_errors_div").removeClass("hidden");
		$form.find('payment_error').text(response.error.message);
		$form.find('button').prop('disabled', false);
	} else {
		$("#Card_errors_div").addClass("hidden");
		// response contains id and card which contains additional card details
		var token = response.id;
		//insert the token into the form so it gets submitted to the server
		$form.append($('<input-type-"hidden" name="stripeToken" />').val(token));
		//and submit
		$form.get(0).submit();
	}

	};

$("#addShippingAddress").click(function(e){
	e.preventDefault();
	$("#shippingAddressForm").fadeToggle();
})

{% if not cutrrent_addreses %}
	$("#shippingAddressForm").fadeToggle();
{% endif %}

{% endblock %}
</script>


<style>
{% block styles %}

.radio-label {
  font-size: 22px;
  font-weight: normal;
  padding: 4px 30px;
  border: 1px solid #ccc;
  border-radius: 8px;
}

.radio-label input[type=radio] {
  display: none;
}

.radio-label:hover {
  font-size: 22px;
  font-weight: normal;
  background-color: #428bca;
  color: white;
  cursor: pointer;

}

.radio-label-selected {
  font-size: 22px;
  font-weight: normal;
  background-color: #428bca;
  color: white;
  cursor: pointer;
}

.billing-label {
  font-size: 22px;
  font-weight: normal;
  padding: 4px 30px;
  border: 1px solid #ccc;
  border-radius: 8px;
}

.billing-label input[type=radio] {
  display: none;
}

.billing-label:hover {
  font-size: 22px;
  font-weight: normal;
  background-color: #428bca;
  color: white;
  cursor: pointer;

}

.billing-label-selected {
  font-size: 22px;
  font-weight: normal;
  background-color: #428bca;
  color: white;
  cursor: pointer;
}




@media(min-width: 1200px) {
  .total { 
    position: fixed;
  }
}

{% endblock %}
</style>


{% block content %}

<div class='col-sm-3 pull-right'>
<div class='total'>
<h1>Current total: {{ order.get_final_amount }}</h1>
<a href='#'>Finalize Checkout</a>
</div>
</div>

<div class='col-sm-9 pull-left'>

        <div class='col-sm-6 pull-right' id='shippingAddressForm' style='display:none;'>
        <h3>Add new Shipping Address</h3>
        <form method="POST" action='{% url "ajax_add_user_address" %}?next=checkout'>{% csrf_token %}
        {{ address_form.as_p }}

        <input type='submit' class='btn btn-default' value='Add Shipping Address'/>
        </form>
        </div>





        <form method='POST' action="" id="payment-form"> {% csrf_token %}
        {% if current_addresses  %}
        <div class='col-sm-12'>
        <h3>Shipping Addresses</h3>
         
            {% for address in current_addresses %}
            
            {% if request.user.userdefaultaddress.shipping.id == address.id %} 
             <label class='radio-label radio-label-selected'>
            <input type='radio' name='shipping_address' value='{{ address.id }}' checked='checked'/> {{ address.get_address }} 
            {% else %}
             <label class='radio-label'>
            <input type='radio' name='shipping_address' value='{{ address.id }}' /> {{ address.get_address }}

            {% endif %}
              </label><br/>
            {% endfor %}
        

        <a href='{% url "add_user_address" %}' id='addShippingAddress'>Add New Address</a>
        </div>
        {% endif %}




  

        {% if billing_addresses  %}
        <div class='col-sm-12'>
        <h3>Billing Addresses</h3>

        
              {% for address in billing_addresses %}
               
              {% if request.user.userdefaultaddress.billing.id == address.id %} 
                <label class='billing-label billing-label-selected'>
              <input type='radio' name='billing_address' value='{{ address.id }}' checked='checked'/> {{ address.get_address }} <br/>
              {% else %}
              <label class='billing-label'>
              <input type='radio' name='billing_address' value='{{ address.id }}' /> {{ address.get_address }} <br/>

              {% endif %}
                </label>
              {% endfor %}
            
        </div>
        {% endif %}

        <div class='col-sm-6'>
        <h3>Credit Info</h3>
          <div id='card_errors_div' class="alert alert-danger hidden payment-errors" role="alert">
          </div>

          <div class="form-row">
            <div class='row'>
            <div class='col-xs-6' style='padding-right:0px;'>
            <b>Card Number</b>
              <input class='form-control' type="text" size="20" data-stripe="number"/>
            </div>
            <div class='col-xs-2'>
             <b>CVC</b>
              <input class='form-control' type="text" size="4" data-stripe="cvc"/>

            </div>

            </div>

          </div>
          <br/>

          <div class="form-row">
            <b>Expiration (MM/YYYY)</b>
            <div class='row'>

            <div class='col-xs-2' style='padding-right:0px;'>
                  <input class='form-control'  type="text" size="2" data-stripe="exp-month" placeholder='2'/>
                </div>
                <div class='col-xs-3'>
                <input  class='form-control' type="text" size="4" data-stripe="exp-year" placeholder='2017'/>
                </div>
            </div>
          </div>
          <br/>
          <br/>
          <button class='btn btn-default btn-lg' type="submit">Submit Payment</button>




  
        </div>
        </form>
</div>
{% endblock %}

templates/orders/user.html
{% extends "base.html" %}

{% block content %}

{{ user.order_set.all }}

{% endblock %}